[package]
name = "waplc"
version = "0.2.8"
edition = "2024"

[dependencies]
inkwell = { version = "0.7.1", features = ["llvm21-1"] }
clap = { version = "4", features = ["derive"] }
colored = "2"

[[bin]]
name = "waplc"